### ISSUE TITLE
Entity climate.01:215596 (<class 'custom_components.ramses_cc.climate.RamsesController'>) implements HVACMode(s): heat, off, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature.

### ISSUE THREAD

**Issue by RedEarth1** [zxdavb/ramses_cc#179] opened 2024-03-22 15:09 UTC
**Describe the bug**
Upon each restart of HA, I get this warning in the log:

`Entity climate.01:215596 (<class 'custom_components.ramses_cc.climate.RamsesController'>) implements HVACMode(s): heat, off, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature.`

I'm not entirely sure what it means, and it doesn't appear to be causing any functional problems

**To Reproduce**
1. Restart HA
2. Check HA log
3. See waning

**Versions**
HA Core 2024.3.2
Supervisor 2024.03.0
HAOS 12.1
Frontend 20240307.0
RAMSES RF 0.41.7

**Please complete the following information:**
 - `ramses_cc:` section from **configuration.yaml**
(not applicable, using config flow)

 - contemporaneous portion of the **home-assistant.log**
`2024-03-22 12:52:29.034 WARNING (MainThread) [ramses_rf.gateway] GATEWAY: Restored, resuming
2024-03-22 12:52:29.078 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up ramses_cc.binary_sensor
2024-03-22 12:52:29.139 INFO (MainThread) [homeassistant.components.sensor] Setting up ramses_cc.sensor
2024-03-22 12:52:29.205 INFO (MainThread) [homeassistant.components.climate] Setting up ramses_cc.climate
2024-03-22 12:52:29.214 INFO (MainThread) [homeassistant.components.generic_thermostat.climate] Obtained current and target temperature. Generic thermostat active. 20.46, 21.0
2024-03-22 12:52:29.216 INFO (MainThread) [homeassistant.components.generic_thermostat.climate] Obtained current and target temperature. Generic thermostat active. 20.18, 21.0
2024-03-22 12:52:29.218 WARNING (MainThread) [homeassistant.components.climate] Entity climate.01:215596 (<class 'custom_components.ramses_cc.climate.RamsesController'>) implements HVACMode(s): heat, off, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/zxdavb/ramses_cc/issues
2024-03-22 12:52:29.274 INFO (MainThread) [homeassistant.components.water_heater] Setting up ramses_cc.water_heater`

 - contemporaneous portion of the **packet.log**
`2024-03-22T12:52:28.600196 # ramses_tx 0.31.7
2024-03-22T12:52:28.705359 000  I --- 18:138258 63:262142 --:------ 7FFF 015 0010018E6638497376302E33312E37
2024-03-22T12:52:28.731297 ... RP --- 01:215596 18:138258 --:------ 000C 006 00047FFFFFFF # 000C|RP|01:215596|0004 (0004)
2024-03-22T12:52:28.739967 ...  I --- 01:215596 --:------ 01:215596 1100 008 FC180400007FFF01 # 1100| I|01:215596|FC (FC)
2024-03-22T12:52:28.748769 ...  I --- 04:038781 --:------ 01:215596 1060 003 026401 # 1060| I|04:038781|02 (02)
2024-03-22T12:52:28.758230 ...  I --- 04:038781 --:------ 04:038781 1060 003 006401 # 1060| I|04:038781
2024-03-22T12:52:28.778419 ...  I --- 04:038783 --:------ 01:215596 1060 003 006401 # 1060| I|04:038783|00 (00)
2024-03-22T12:52:28.783036 ...  I --- 04:038783 --:------ 04:038783 1060 003 006401 # 1060| I|04:038783
2024-03-22T12:52:28.799966 ...  I --- 04:038777 --:------ 01:215596 1060 003 036401 # 1060| I|04:038777|03 (03)
2024-03-22T12:52:28.809656 ...  I --- 04:038777 --:------ 04:038777 1060 003 006401 # 1060| I|04:038777
2024-03-22T12:52:28.812043 ... RP --- 01:215596 18:138258 --:------ 0005 004 000B0000 # 0005|RP|01:215596|000B (000B)
2024-03-22T12:52:28.820425 ... RP --- 01:215596 18:138258 --:------ 000C 006 030400109779 # 000C|RP|01:215596|0304 (0304)
2024-03-22T12:52:28.822878 ... RP --- 01:215596 18:138258 --:------ 000C 006 04040012A17F # 000C|RP|01:215596|0404 (0404)
2024-03-22T12:52:28.827378 ...  I --- 13:129802 --:------ 13:129802 1100 008 00180400007FFF01 # 1100| I|13:129802
2024-03-22T12:52:28.829695 ... RP --- 01:215596 18:138258 --:------ 000C 006 02040010977D # 000C|RP|01:215596|0204 (0204)
2024-03-22T12:52:28.831267 ... RP --- 01:215596 18:138258 --:------ 0005 004 00081F00 # 0005|RP|01:215596|0008 (0008)
2024-03-22T12:52:28.834084 ... RP --- 01:215596 18:138258 --:------ 0005 004 00090000 # 0005|RP|01:215596|0009 (0009)
2024-03-22T12:52:28.839492 ... RP --- 01:215596 18:138258 --:------ 000C 006 02080010977D # 000C|RP|01:215596|0208 (0208)
2024-03-22T12:52:28.841390 ... RP --- 01:215596 18:138258 --:------ 000C 006 000D7FFFFFFF # 000C|RP|01:215596|000D (000D)
2024-03-22T12:52:28.846301 ... RP --- 01:215596 18:138258 --:------ 000C 006 000E7FFFFFFF # 000C|RP|01:215596|000E (000E)
2024-03-22T12:52:28.849715 ... RP --- 01:215596 18:138258 --:------ 000C 006 010E7FFFFFFF # 000C|RP|01:215596|010E (010E)
2024-03-22T12:52:28.851700 ... RP --- 01:215596 18:138258 --:------ 000A 006 031001F409C4 # 000A|RP|01:215596|03 (03)
2024-03-22T12:52:28.854489 ... RP --- 13:129802 18:138258 --:------ 1100 008 00180400007FFF01 # 1100|RP|13:129802
2024-03-22T12:52:28.858130 ... RP --- 01:215596 18:138258 --:------ 0004 022 01004B69746368656E00000000000000000000000000 # 0004|RP|01:215596|01 (01)
2024-03-22T12:52:28.860998 ... RP --- 01:215596 18:138258 --:------ 0004 022 040042617468726F6F6D000000000000000000000000 # 0004|RP|01:215596|04 (04)
2024-03-22T12:52:28.864305 ...  I --- 04:038779 --:------ 01:215596 1060 003 016401 # 1060| I|04:038779|01 (01)
2024-03-22T12:52:28.867754 ...  I --- 04:038779 --:------ 04:038779 1060 003 006401 # 1060| I|04:038779
2024-03-22T12:52:28.869774 ... RP --- 01:215596 18:138258 --:------ 1100 008 FC180400007FFF01 # 1100|RP|01:215596|FC (FC)
2024-03-22T12:52:28.871713 ... RP --- 01:215596 18:138258 --:------ 30C9 003 03082F # 30C9|RP|01:215596|03 (03)
2024-03-22T12:52:28.875090 ... RP --- 01:215596 18:138258 --:------ 30C9 003 010767 # 30C9|RP|01:215596|01 (01)
2024-03-22T12:52:28.878234 ... RP --- 01:215596 18:138258 --:------ 000C 006 000F0035FB0A # 000C|RP|01:215596|000F (000F)
2024-03-22T12:52:28.880799 ... RP --- 01:215596 18:138258 --:------ 000C 006 030800109779 # 000C|RP|01:215596|0308 (0308)
2024-03-22T12:52:28.883071 ... RP --- 01:215596 18:138258 --:------ 000C 006 01080010977B # 000C|RP|01:215596|0108 (0108)
2024-03-22T12:52:28.886969 ... RP --- 01:215596 18:138258 --:------ 000C 006 04080012A17F # 000C|RP|01:215596|0408 (0408)
2024-03-22T12:52:28.890018 ... RP --- 01:215596 18:138258 --:------ 000C 006 00080010977F # 000C|RP|01:215596|0008 (0008)
2024-03-22T12:52:28.892883 ... RP --- 01:215596 18:138258 --:------ 0005 004 000A0000 # 0005|RP|01:215596|000A (000A)
2024-03-22T12:52:28.896256 ... RP --- 01:215596 18:138258 --:------ 000C 006 01040010977B # 000C|RP|01:215596|0104 (0104)
2024-03-22T12:52:28.899196 ... RP --- 01:215596 18:138258 --:------ 0005 004 00110000 # 0005|RP|01:215596|0011 (0011)
2024-03-22T12:52:28.901922 ... RP --- 01:215596 18:138258 --:------ 0005 004 00041F00 # 0005|RP|01:215596|0004 (0004)
2024-03-22T12:52:28.904372 ... RP --- 01:215596 18:138258 --:------ 0004 022 00004C6F756E67650000000000000000000000000000 # 0004|RP|01:215596|00 (00)
2024-03-22T12:52:28.908575 ... RP --- 01:215596 18:138258 --:------ 0004 022 0200426564726F6F6D20310000000000000000000000 # 0004|RP|01:215596|02 (02)
2024-03-22T12:52:28.910828 ... RP --- 01:215596 18:138258 --:------ 0004 022 0300426564726F6F6D20320000000000000000000000 # 0004|RP|01:215596|03 (03)
2024-03-22T12:52:28.913454 ... RP --- 01:215596 18:138258 --:------ 10A0 006 007FFF007FFF # 10A0|RP|01:215596|00 (00)
2024-03-22T12:52:28.917387 ...  I --- 04:038779 --:------ 01:215596 2309 003 010578 # 2309| I|04:038779|01 (01)
2024-03-22T12:52:28.920942 ... RP --- 01:215596 04:172415 --:------ 0100 005 00656EFFFF # 0100|RP|01:215596
2024-03-22T12:52:28.923893 ...  I --- 04:172415 --:------ 01:215596 1060 003 046401 # 1060| I|04:172415|04 (04)
2024-03-22T12:52:28.925937 ...  I --- 04:172415 --:------ 04:172415 1060 003 006401 # 1060| I|04:172415
2024-03-22T12:52:28.927781 ...  I --- 04:172415 --:------ 01:215596 12B0 003 040000 # 12B0| I|04:172415|04 (04)
2024-03-22T12:52:28.930147 ...  I --- 04:172415 --:------ 01:215596 2309 003 040708 # 2309| I|04:172415|04 (04)
2024-03-22T12:52:28.931847 ...  I --- 04:038783 --:------ 01:215596 12B0 003 000000 # 12B0| I|04:038783|00 (00)
2024-03-22T12:52:28.933949 ...  I --- 01:215596 --:------ 01:215596 000A 030 001001F409C4011001F409C4021001F409C4031001F409C4041201F40DAC # 000A| I|01:215596 (True)
2024-03-22T12:52:28.936944 ...  I --- 04:038779 --:------ 01:215596 12B0 003 010000 # 12B0| I|04:038779|01 (01)
2024-03-22T12:52:28.939314 ... RP --- 01:215596 18:138258 --:------ 30C9 003 040824 # 30C9|RP|01:215596|04 (04)
2024-03-22T12:52:28.941089 ... RP --- 01:215596 18:138258 --:------ 30C9 003 00079C # 30C9|RP|01:215596|00 (00)
2024-03-22T12:52:28.943030 ... RP --- 01:215596 18:138258 --:------ 30C9 003 020804 # 30C9|RP|01:215596|02 (02)
2024-03-22T12:52:28.945104 ...  I --- 04:038781 --:------ 01:215596 2309 003 0207D0 # 2309| I|04:038781|02 (02)
2024-03-22T12:52:28.947113 ...  I --- 04:038783 --:------ 04:038783 30C9 003 00070C # 30C9| I|04:038783
2024-03-22T12:52:28.951233 ...  I --- 04:038779 --:------ 04:038779 30C9 003 000758 # 30C9| I|04:038779
2024-03-22T12:52:28.952982 ...  I --- 04:038777 --:------ 04:038777 30C9 003 0007E2 # 30C9| I|04:038777
2024-03-22T12:52:28.955000 ...  I --- 04:038781 --:------ 04:038781 30C9 003 0007FE # 30C9| I|04:038781
2024-03-22T12:52:28.956780 ...  I --- 04:038777 --:------ 01:215596 12B0 003 030000 # 12B0| I|04:038777|03 (03)
2024-03-22T12:52:28.958574 ...  I --- 04:038781 --:------ 01:215596 12B0 003 020000 # 12B0| I|04:038781|02 (02)
2024-03-22T12:52:28.960516 ...  I --- 04:038779 --:------ 01:215596 3150 002 0118 # 3150| I|04:038779|01 (01)
2024-03-22T12:52:28.963420 ...  I --- 01:215596 --:------ 01:215596 0008 002 FC00 # 0008| I|01:215596|FC (FC)
2024-03-22T12:52:28.966611 ...  I --- 01:215596 --:------ 01:215596 3150 002 FC00 # 3150| I|01:215596|FC (FC)
2024-03-22T12:52:28.968507 ... RP --- 13:129802 18:138258 --:------ 0008 002 0000 # 0008|RP|13:129802
2024-03-22T12:52:28.970873 ... RP --- 01:215596 18:138258 --:------ 1260 003 007FFF # 1260|RP|01:215596|00 (00)
2024-03-22T12:52:28.973223 ...  I --- 04:172415 --:------ 04:172415 30C9 003 000811 # 30C9| I|04:172415
2024-03-22T12:52:28.975502 ... RP --- 01:215596 18:138258 --:------ 12B0 003 010000 # 12B0|RP|01:215596|01 (01)
2024-03-22T12:52:28.977297 ...  I --- 04:038777 --:------ 01:215596 2309 003 0307D0 # 2309| I|04:038777|03 (03)
2024-03-22T12:52:28.979333 ...  I --- 13:129802 --:------ 13:129802 3B00 002 00C8 # 3B00| I|13:129802
2024-03-22T12:52:28.981753 ...  I --- 13:129802 --:------ 13:129802 3EF0 003 0000FF # 3EF0| I|13:129802
2024-03-22T12:52:28.984776 ...  I --- 01:215596 --:------ 01:215596 3B00 002 FCC8 # 3B00| I|01:215596|FC (FC)
2024-03-22T12:52:28.986826 ... RP --- 01:215596 18:138258 --:------ 12B0 003 020000 # 12B0|RP|01:215596|02 (02)
2024-03-22T12:52:28.988620 ... RP --- 01:215596 18:138258 --:------ 12B0 003 040000 # 12B0|RP|01:215596|04 (04)
2024-03-22T12:52:28.990471 ... RP --- 01:215596 18:138258 --:------ 12B0 003 000000 # 12B0|RP|01:215596|00 (00)
2024-03-22T12:52:28.992297 ... RP --- 01:215596 18:138258 --:------ 12B0 003 030000 # 12B0|RP|01:215596|03 (03)
2024-03-22T12:52:28.994278 ...  I --- 04:038783 --:------ 01:215596 3150 002 0000 # 3150| I|04:038783|00 (00)
2024-03-22T12:52:28.996288 ...  I --- 04:172415 --:------ 01:215596 3150 002 0400 # 3150| I|04:172415|04 (04)
2024-03-22T12:52:28.997905 ...  I --- 04:038781 --:------ 01:215596 3150 002 0200 # 3150| I|04:038781|02 (02)
2024-03-22T12:52:28.999654 ...  I --- 04:038777 --:------ 01:215596 3150 002 0300 # 3150| I|04:038777|03 (03)
2024-03-22T12:52:29.001524 ... RP --- 01:215596 18:138258 --:------ 0006 004 0005000C # 0006|RP|01:215596
2024-03-22T12:52:29.003919 ... RP --- 01:215596 18:138258 --:------ 0418 022 000000B0000000000000000000007FFFFF7000000000 # 0418|RP|01:215596|00 (00)
2024-03-22T12:52:29.007070 ... RP --- 01:215596 18:138258 --:------ 2E04 008 00FFFFFFFFFFFF00 # 2E04|RP|01:215596
2024-03-22T12:52:29.009444 ...  I --- 01:215596 --:------ 01:215596 1F09 003 FF0852 # 1F09| I|01:215596
2024-03-22T12:52:29.011882 ...  I --- 01:215596 --:------ 01:215596 2309 015 0005DC01076C0207D00307D0040708 # 2309| I|01:215596 (True)
2024-03-22T12:52:29.013545 ...  I --- 01:215596 --:------ 01:215596 30C9 015 0007AE0107580207FE0307E2040811 # 30C9| I|01:215596 (True)
2024-03-22T12:52:29.015785 ... RP --- 13:129802 18:138258 --:------ 3EF1 007 000063006300FF # 3EF1|RP|13:129802
2024-03-22T12:52:29.019052 ... RP --- 01:215596 18:138258 --:------ 2349 007 02080200FFFFFF # 2349|RP|01:215596|02 (02)
2024-03-22T12:52:29.021986 ... RP --- 01:215596 18:138258 --:------ 1F41 006 00FF00FFFFFF # 1F41|RP|01:215596|00 (00)
2024-03-22T12:52:29.025425 ... RP --- 01:215596 18:138258 --:------ 2349 007 0005DC00FFFFFF # 2349|RP|01:215596|00 (00)
2024-03-22T12:52:29.027857 ... RP --- 01:215596 18:138258 --:------ 2349 007 03080200FFFFFF # 2349|RP|01:215596|03 (03)
2024-03-22T12:52:29.030059 ... RP --- 01:215596 18:138258 --:------ 2349 007 01076C00FFFFFF # 2349|RP|01:215596|01 (01)
2024-03-22T12:52:29.032080 ... RP --- 01:215596 18:138258 --:------ 2349 007 04070800FFFFFF # 2349|RP|01:215596|04 (04)
2024-03-22T12:52:29.186917 000 RQ --- 18:138258 13:129802 --:------ 0008 001 00
2024-03-22T12:52:29.188818 048 RP --- 13:129802 18:138258 --:------ 0008 002 0000
2024-03-22T12:52:29.281921 000 RQ --- 18:138258 13:129802 --:------ 3EF1 001 00
2024-03-22T12:52:29.284685 048 RP --- 13:129802 18:138258 --:------ 3EF1 007 000213021300FF
2024-03-22T12:52:29.359904 000 RQ --- 18:138258 01:215596 --:------ 313F 001 00
2024-03-22T12:52:29.373874 000 RQ --- 18:138258 01:215596 --:------ 000C 002 000D
2024-03-22T12:52:29.383892 000 RQ --- 18:138258 01:215596 --:------ 000C 002 000E
2024-03-22T12:52:29.401817 053 RP --- 01:215596 18:138258 --:------ 000C 006 000E7FFFFFFF
2024-03-22T12:52:29.414159 000 RQ --- 18:138258 01:215596 --:------ 000C 002 010E
2024-03-22T12:52:29.421854 000 RQ --- 18:138258 01:215596 --:------ 1260 001 00
2024-03-22T12:52:29.528855 063  I --- 04:038777 --:------ 01:215596 3150 002 0322
2024-03-22T12:52:34.310439 000 RQ --- 18:138258 01:215596 --:------ 0418 003 000000
2024-03-22T12:52:34.328972 053 RP --- 01:215596 18:138258 --:------ 0418 022 000000B0000000000000000000007FFFFF7000000000
2024-03-22T12:52:37.308910 000 RQ --- 18:138258 01:215596 --:------ 2E04 001 FF
2024-03-22T12:52:37.317892 000 RQ --- 18:138258 01:215596 --:------ 0006 001 00
2024-03-22T12:52:37.542899 000 RQ --- 18:138258 01:215596 --:------ 0006 001 00
2024-03-22T12:52:37.555862 054 RP --- 01:215596 18:138258 --:------ 0006 004 0005000C
2024-03-22T12:52:48.009899 061  I --- 04:038779 --:------ 01:215596 2309 003 01076C`

**Comment by zxdavb** [comment] 2024-03-29 20:50
duplicate of #162

**Closed by zxdavb** 2024-03-29 20:50 UTC
